import type { Metadata } from "next";
import { Raleway } from "next/font/google";
// import { Header } from "./ui/header";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import "../app/ui/globals.css";

const inter = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-desertStorm`}>
        <UserProvider>
          {/* <Header /> */}
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
